### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by gjay97** [gjolps/hello-world#2]
Test issue. Just checking out code comments. 

`
print("Hello World")
`

**Comment by gjolps** [comment]
`panic: runtime error: slice bounds out of range [:102] with length 100

goroutine 148 [running]:
github.com/k8spacket/k8spacket/ebpf/tc.distribute({0xafe7d53, 0xafedb5b, 0xaae4, 0x20f0, 0x303, 0x4, {0x0}, {0x304, 0x303, 0x2d, ...}, ...})
/home/k8spacket/ebpf/tc/tc.go:146 +0x29e
github.com/k8spacket/k8spacket/ebpf/tc.Init.func1()
/home/k8spacket/ebpf/tc/tc.go:97 +0x1b8
created by github.com/k8spacket/k8spacket/ebpf/tc.Init in goroutine 116
/home/k8spacket/ebpf/tc/tc.go:77 +0x3fb`

**Comment by gjolps** [comment]
```
func distribute(event tcTlsHandshakeEvent) {

tlsVersionsLen := int(event.TlsVersionsLength)/2
if tlsVersionsLen > len(event.TlsVersions) {
    	tlsVersionsLen = len(event.TlsVersions)
	}

	ciphersLen := int(event.CiphersLength)/2
if ciphersLen > len(event.Ciphers) {
    	ciphersLen = len(event.Ciphers)
	}

	serverNameLen := int(event.ServerNameLength)
if serverNameLen > len(event.ServerName){
	serverNameLen = len(event.ServerName)
}

tlsEvent := plugin_api.TLSEvent{
	Client: plugin_api.Address{
		Addr: intToIP4(event.Saddr),
		Port: event.Sport},
	Server: plugin_api.Address{
		Addr: intToIP4(event.Daddr),
		Port: event.Dport},
	TlsVersions:    event.TlsVersions[:tlsVersionsLen],
	Ciphers:        event.Ciphers[:ciphersLen],
	ServerName:     string(event.ServerName[:serverNameLen]),
	UsedTlsVersion: event.UsedTlsVersion,
	UsedCipher:     event.UsedCipher}
ebpf_tools.EnrichAddress(&tlsEvent.Client)
ebpf_tools.EnrichAddress(&tlsEvent.Server)
broker.TLSEvent(tlsEvent)
}
```

**Comment by gjay97** [comment]
Multi-line code 

```
print("Hello World")
print("This is an example of pasting multi line code in git")
```

**Comment by gjay97** [comment]
Test complete
